"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-en#dope6fag9gxbo80f(fjk&1deb=eh%e$#abak%vg^cl$t4$('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # required for django to load the functionality it needs to deal with static files
    'django_extensions',  # This is for the runscript functionality to load data into the database.
    'module'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates" # Ensures that Django looks in the templates folder of the main app project for any html templates.
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# These values are used in the html pages when setting the options of the dropdown. They are also used when we create the initial data in the database as the tag values
# so that when we try to filter we dont run into case sensitivity issues.
CONFIG_VALUES =   {
                "nonsmokervalue" : "NON SMOKER",
                "heavysmokervalue" : "HEAVY SMOKER",
                "lightsmokervalue": "LIGHT SMOKER",
                "nondrinkervalue" : "NON DRINKER",
                "regulardrinkervalue" : "REGULAR DRINKER",
                "occasionaldrinkervalue": "OCCASIONAL DRINKER",
                "previnfection_yes" : "PREVIOUS INFECTION YES",
                "previnfection_no": "PREVIOUS INFECTION NO",
                "bloodexposure_yes" : "BLOOD EXPOSURE YES",
                "bloodexposure_no": "BLOOD EXPOSURE NO",
                "menstrualhistory_allgood": "MENSTRUAL HISTORY ALL GOOD",
                "menstrualhistory_excessivebleeding" : "MENSTRUAL HISTORY EXCESSIVE BLEEDING",
                "menstrualhistory_ireregularperiods": "MENSTRUAL HISTORY IRREGULAR PERIODS",
                "gender_male": "MALE",
                "gender_female" : "FEMALE",
                "age_range_old" : "OLD",
                "age_range_young" : "YOUNG",
                "testtype_healthcheckup" : "GENERAL HEALTH CHECKUP",
                "testtype_personalised" : "PERSONALISED",

            }
