# Generated by Django 4.0.10 on 2024-06-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='caption',
            new_name='tagname',
        ),
    ]
