# Generated by Django 4.0.10 on 2024-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_diagnostictest_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictest',
            name='tags',
            field=models.ManyToManyField(null=True, to='module.tag'),
        ),
    ]
