# Generated by Django 4.0.10 on 2024-06-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
