# Generated by Django 4.0.10 on 2024-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='drinkingstatus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='menstrualhistory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previnfection_hbv',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previnfection_hcv',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previnfection_hiv',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smokingstatus',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
