# Generated by Django 4.0.10 on 2024-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_alter_patient_menstrualhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodexposure',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
