# Generated by Django 4.0.10 on 2024-06-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0014_alter_patient_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_range',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
