# Generated by Django 4.0.10 on 2024-06-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0015_patient_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictest',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
