# Generated by Django 4.0.10 on 2024-06-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0016_alter_diagnostictest_name_alter_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
