# Generated by Django 4.0.10 on 2024-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0017_alter_tag_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
