# Generated by Django 4.0.10 on 2024-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0018_diagnostictest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='validity_days',
            field=models.IntegerField(null=True),
        ),
    ]
