# Generated by Django 4.0.10 on 2024-06-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0020_alter_diagnostictest_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_range',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodexposure',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drinkingstatus',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='menstrualhistory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previnfection',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smokingstatus',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
