# Generated by Django 4.0.10 on 2024-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0021_alter_patient_age_range_alter_patient_bloodexposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='displayicon',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
