# Generated by Django 4.0.10 on 2024-06-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0022_diagnostictest_displayicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='specialinstructions',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
