# Generated by Django 4.0.10 on 2024-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0023_diagnostictest_specialinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='samplerequirements',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='specialinstructions',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
