# Generated by Django 4.0.10 on 2024-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0024_diagnostictest_samplerequirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='reportavailability',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
