# Generated by Django 4.0.10 on 2024-07-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0025_diagnostictest_reportavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponses',
            fields=[
                ('smokingstatus', models.CharField(blank=True, max_length=150)),
                ('drinkingstatus', models.CharField(blank=True, max_length=150)),
                ('previnfection', models.CharField(blank=True, max_length=150)),
                ('menstrualhistory', models.CharField(blank=True, max_length=150, null=True)),
                ('bloodexposure', models.CharField(blank=True, max_length=150)),
                ('comments', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='module.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bloodexposure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='drinkingstatus',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='menstrualhistory',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='previnfection',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='smokingstatus',
        ),
    ]
